name: 06 - Scheduled Run

on:
  schedule:
    - cron: '* * * * *'      # every day at 02:00 UTC
     # every Monday at 09:00 UTC

jobs:
  scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Nightly housekeeping
        run: echo "Running scheduled job at $(date -u)"
